In [50]:
from rtb_toolbox.robots.comau import comau_fk
from rtb_toolbox.inverse_kinematics import evolutive_ik, full_ik

import numpy as np
from math import pi

theta, f = evolutive_ik(
    np.array([585.95, -585.95, 250.96, 0, pi, pi/4]),
    comau_fk,
    max_iterations=1024
)

theta, f

(array([ 0.785398,  0.645778, -2.18167 , -0.      ,  0.314145, -6.283185]),
 2.76819732127866e-08)

In [51]:
np.rad2deg(theta)

array([  45.      ,   37.000368, -125.000472,   -0.000002,   17.999162,
       -360.000003])

In [52]:
np.set_printoptions(suppress=True, precision=6)
comau_fk.compute_ee_transformation_matrix(
    np.deg2rad([45, 37, -125, 0, 18, 0])
)

array([[  -0.707107,    0.707107,   -0.      ,  585.953819],
       [   0.707107,    0.707107,    0.      , -585.953819],
       [   0.      ,   -0.      ,   -1.      ,  250.96702 ],
       [   0.      ,    0.      ,    0.      ,    1.      ]])