In [1]:
from rtb_toolbox.robots.comau import comau_fk
from rtb_toolbox.inverse_kinematics import evolutive_ik, full_ik

import numpy as np
from math import pi

theta, f = evolutive_ik(
    np.array([537.134122, 537.134122, 295.794, 0, pi, -pi/4]),
    comau_fk,
    max_iterations=1024
)

theta, f

(array([-0.78539816,  0.50614381, -2.32130249,  3.14159262, -0.31414637,
         3.1415926 ]),
 3.545383195141587e-08)

In [2]:
np.rad2deg(theta)

array([ -45.00000007,   28.99990386, -133.00083562,  179.99999818,
        -17.99926087,  179.99999672])

In [3]:
np.set_printoptions(suppress=True, precision=6)
comau_fk.compute_ee_transformation_matrix(
    theta
)

array([[ -0.707107,  -0.707107,  -0.      , 537.134122],
       [ -0.707107,   0.707107,   0.      , 537.134122],
       [  0.      ,   0.      ,  -1.      , 295.794   ],
       [  0.      ,   0.      ,   0.      ,   1.      ]])