In [7]:
from rtb_toolbox.robots.comau import comau_fk
from rtb_toolbox.inverse_kinematics import evolution_ik, full_ik
  
import numpy as np
from math import pi

theta, f = full_ik(
    np.array([537.95, -537.95, 295.96, 0, pi, pi/4]),
    comau_fk,
    max_iterations=1024
)

theta, f

(array([ 0.78524689,  2.82729927,  1.92262224,  3.14005135, -2.23659436,
        -3.14021357]),
 0.001466713536074683)

In [8]:
np.rad2deg(theta)

array([  44.99133276,  161.99231531,  110.15813993,  179.91168993,
       -128.14741702, -179.92098429])

In [9]:
np.set_printoptions(suppress=True, precision=6)
comau_fk.compute_ee_transformation_matrix(
    theta
)

array([[  -0.706912,    0.707301,    0.001084,  537.949607],
       [   0.707302,    0.706912,    0.00063 , -537.949702],
       [  -0.00032 ,    0.001212,   -0.999999,  295.960509],
       [   0.      ,    0.      ,    0.      ,    1.      ]])