In [11]:
from rtb_toolbox.robots.comau import comau_fk
from rtb_toolbox.inverse_kinematics import evolutive_ik, full_ik

import numpy as np
from math import pi

theta, f = evolutive_ik(
    np.array([537.134122, 537.134122, 295.794, 0, pi, -pi/4]),
    comau_fk,
    max_iterations=1024
)

theta, f

(array([-0.785398,  0.506144, -2.321302,  0.      ,  0.314146,  6.283185]),
 3.675305358494694e-08)

In [12]:
np.rad2deg(theta)

array([ -45.      ,   28.999904, -133.000836,    0.000001,   17.99926 ,
        360.000001])

In [13]:
np.set_printoptions(suppress=True, precision=6)
comau_fk.compute_ee_transformation_matrix(
    theta
)

array([[ -0.707107,  -0.707107,   0.      , 537.134122],
       [ -0.707107,   0.707107,  -0.      , 537.134122],
       [ -0.      ,  -0.      ,  -1.      , 295.794   ],
       [  0.      ,   0.      ,   0.      ,   1.      ]])